### ISSUE TITLE
Source cannot run on 8086

### ISSUE THREAD

**Issue by MobyGamer** [sourcerer-io/retrokern#1]
The readme for this project states "will boot (in theory) in any 8086 or later CPU" but the very first instruction of console.asm is PUSHA.  PUSHA/POPA are 80286 instructions and are invalid on an 8086 CPU.

pusha/popa are also found in timer.asm, game.asm, and video.asm.

(Could be fixed as a pull request, but your article seemed very much focused on self-discovery, so I am leaving it to you to determine exactly which registers should be pushed and popped, or whether you want to create a "_pusha"/"_popa" macro.  I don't recommend the macro.)

**Comment by rwoliver2** [comment]
Hi Jim,

Yes, the macro could be a problem.

Looks like the 80186 and higher support PUSHA/POPA. I can just push/pop the individual registers. A simple fix.

Thanks for bringing this to my attention.

Robert

**Comment by rwoliver2** [comment]
Fixed and tested.
